project_id = "gerodpwicbuukllgkmzg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch.services]]
name = "resend"
url = "https://api.resend.com"