// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gerodpwicbuukllgkmzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlcm9kcHdpY2J1dWtsbGdrbXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NDg1NjUsImV4cCI6MjA1MjUyNDU2NX0.OLP40tre6vxUmCHNsRfzsIOYcBCqly3XLtCZ6PiryeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);